/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/competitions/[competitionId]` | `/competitions/[competitionId]`, params: Router.UnknownInputParams & { competitionId: string | number; } } | { pathname: `${'/(tabs)'}/competitions/[competitionId]/acts/[actId]` | `/competitions/[competitionId]/acts/[actId]`, params: Router.UnknownInputParams & { competitionId: string | number;actId: string | number; } } | { pathname: `/users/[userId]`, params: Router.UnknownInputParams & { userId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/competitions/[competitionId]` | `/competitions/[competitionId]`, params: Router.UnknownOutputParams & { competitionId: string; } } | { pathname: `${'/(tabs)'}/competitions/[competitionId]/acts/[actId]` | `/competitions/[competitionId]/acts/[actId]`, params: Router.UnknownOutputParams & { competitionId: string;actId: string; } } | { pathname: `/users/[userId]`, params: Router.UnknownOutputParams & { userId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/competitions/${Router.SingleRoutePart<T>}` | `/competitions/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/competitions/${Router.SingleRoutePart<T>}/acts/${Router.SingleRoutePart<T>}` | `/competitions/${Router.SingleRoutePart<T>}/acts/${Router.SingleRoutePart<T>}` | `/users/${Router.SingleRoutePart<T>}` | { pathname: `${'/(tabs)'}/competitions/[competitionId]` | `/competitions/[competitionId]`, params: Router.UnknownInputParams & { competitionId: string | number; } } | { pathname: `${'/(tabs)'}/competitions/[competitionId]/acts/[actId]` | `/competitions/[competitionId]/acts/[actId]`, params: Router.UnknownInputParams & { competitionId: string | number;actId: string | number; } } | { pathname: `/users/[userId]`, params: Router.UnknownInputParams & { userId: string | number; } };
    }
  }
}
